### ISSUE TITLE
`devices` with constraints returns a list of mixed devices instead of video only

### ISSUE THREAD

**Issue by matthiasprieth** [nomadoda/react-media-devices#1]
Hi,
thx for this module! I just realized, that `devices` returns a list of mixed devices even tough `constraints` was set to video only (I'm using the same code as in your example but audio set to false and video to true).

Pls note that I'm using [1.0.2](https://www.npmjs.com/package/react-media-devices/v/1.0.2), cause 1.1.0 is not on NPM yet. 
```
  const [selectedConstraints, setSelectedConstraints] =
    useState<MediaStreamConstraints>({
      audio: false,
      video: true,
    });
  const devices = useMediaDevices({
    constraints: selectedConstraints,
    onError: (error) => {
      console.error(error);
    },
  });
```

Thx

**Comment by adamkrupke** [comment]
Actually, in its current implementation, it uses the given constraints to request access to devices within those constraints. It always returns all available devices though. I'm not sure if I can safely filter these devices based on given constraints and I'm not convinced it makes sense doing so. Do you have a use case?

**Comment by matthiasprieth** [comment]
Hey thx for the quick response. If that's the default behaviour then better leave it like that. I just expected something else because of the "constraints" naming. But no problem I'll filter it by myself.
