### ISSUE TITLE
List of cameras incomplete for iPhone 13, 14, 14 pro

### ISSUE THREAD

**Issue by matthiasprieth** [nomadoda/react-media-devices#2]
Hey,
sorry to disturb you another time. 

I just realized, that `react-media-devices` does not return all "cameras"/lenses for iPhone 13, 14, 14 pro. It just returns one front and one rear camera (fisheye/rear). iPhone 11 & all androids seem to do fine, but only because the returned rear camera is the "normal" one by default, not the wide/fisheye one.

The problem is that I'm doing barcode scanning and on iPhone's 13+ can't barely scan anything, cause the fisheye/wide angle lens becomes really blurry once you get closer to the barcode with you camera (fixed focal length I guess). 

iPhone 14 Pro:
![image](https://user-images.githubusercontent.com/4509289/207378466-cfbec317-e2f8-4266-a4cc-212353798dc2.png)

So you think it's possible to change between lenses of cameras?
Or do you think this more of a `react-media-devices` problem, a limitation of the native `navigator.mediaDevices.getUserMedia(constraints) ` function, or missing rights from the browser/device itself?

Edit: Also using `constraints: { video: { facingMode: 'environment' }, audio: false }` vs `constraints: { video: true, audio: false }` does not make any difference.

**Comment by matthiasprieth** [comment]
Seems like our hands are tied here: https://developer.apple.com/forums/thread/715568 😭

**Comment by adamkrupke** [comment]
[Might have been fixed in iOS 16.4](https://developer.apple.com/forums/thread/715568?answerId=751906022#751906022). Is this something you could confirm?

**Comment by qcasey** [comment]
Although I didn't experience this issue originally, I'm seeing 7 cameras on an iPhone 14

```
0 Front Camera
1 Back Camera
2 Back Telephoto Camera
3 Back Ultra Wide Camera
4 Desk View Camera
5 Back Dual Wide Camera
6 Back Triple Camera
```

**Comment by adamkrupke** [comment]
Cool, I guess we can probably resolve this then. Let me know if there's still an issue!
